# Generated by Django 5.0.7 on 2024-08-28 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bis_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_address',
            new_name='member_country',
        ),
    ]
