# Generated by Django 5.0.7 on 2024-08-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bis_app', '0002_rename_member_address_member_member_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_country',
            field=models.CharField(max_length=200),
        ),
    ]
